version: '3.5'

networks:
  bootcamp:
    name: bootcamp

volumes:
  bootcamp-volume:

services:

  maven-build:
    image: maven:3.8.1-adoptopenjdk-11
    volumes:
      - .:/usr/src/build
      - bootcamp-volume:/root/.m2
    working_dir: /usr/src/build
    command: mvn clean install

  db-mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: custom_service
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      bootcamp:
        aliases:
          - bootcamp-mysql

  bootcamp-app:
    container_name: rest
    build:
      context: rest
    ports:
      - "8080:8081"
#    volumes:
#      - ./logs:/usr/local/tomcat/logs

    environment:
      USERNAMEBD: ${MYSQL_USER}
      PASSWORD: ${MYSQL_PASSWORD}
      URL: jdbc:mysql://bootcamp-mysql:3306/custom_service?createDatabaseIfNotExist=true&serverTimezone=UTC

    networks:
      bootcamp:
