version: '3.5'

networks:
  bootcamp:
    name: bootcamp

volumes:
  bootcamp:

services:

  db-mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: custom_service
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      default:
        aliases:
          - bootcamp-mysql

  bootcamp-app:
    container_name: rest
    build:
      context: rest
      args:
        version: ${VERSION}
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/usr/local/tomcat/logs

    environment:
      spring_datasource_username: ${MYSQL_USER}
      spring_datasource_password: ${MYSQL_PASSWORD}
      spring_datasource_url: jdbc:mysql://bootcamp-mysql:3306/custom_service?createDatabaseIfNotExist=true&serverTimezone=UTC
      MYSQL_DB: custom_service


